name: place
favicon: null
layout_spectrum: 0.33055145805701613
typography_spectrum: 0.10192835377529263
title: not all those who wander are lost
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#555a54'
    - '#8a8896'
    - '#edceaf'
    - '#afacbd'
    - '#cf7658'
  brandStrength: 0.5625
  lightness: 0.46572790131904185
  saturation: 0.976875887485221
  rhythmicContrast: 0
purpose: []
