title: place ~ not all those who wander are lost
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5006266
  brandStrength: 0.1422575
  lightness: 0.4949875
  brandColors:
    - '#202B3E'
    - '#69737C'
    - '#A8B7CE'
    - '#CA9457'
    - '#98546A'
  rhythmicContrast: 0.4993734
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: place
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.87252
layout_spectrum: 0.50371
