name: place
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49615
title: place ~ not all those who wander are lost
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a4c4b'
    - '#ece3e8'
    - '#a29696'
    - '#bf638a'
    - '#9f3c58'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
