name: place
favicon: null
layout_spectrum: 0.2907268
typography_spectrum: 0.49615
title: place ~ not all those who wander are lost
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#2d3f17'
    - '#e1dfe2'
    - '#bab8bb'
    - '#666b65'
  brandStrength: 0
  lightness: 0.7424812
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
